const USER_LIST_QUERY_KEY = "userList";
const USER_FRIENDS_QUERY_KEY = "userFriends";
const USER_CHAT_QUERY_KEY = "userChat";
const USER_GROUP_QUERY_KEY = "userGroup";
const USER_MESSAGE_QUERY_KEY = "userMessage";
const USER_NOTIFICATION_QUERY_KEY = "userNotification";
const ADMIN_DASHBOARD_STATUS_QUERY_KEY = "adminDashboardStatus";
const ADMIN_USER_LIST_QUERY_KEY = "adminUserList";
const ADMIN_CHAT_LIST_QUERY_KEY = "adminChatList";
const ADMIN_MESSAGE_LIST_QUERY_KEY = "adminMessageList";

export {
  USER_LIST_QUERY_KEY,
  USER_FRIENDS_QUERY_KEY,
  USER_CHAT_QUERY_KEY,
  USER_GROUP_QUERY_KEY,
  USER_MESSAGE_QUERY_KEY,
  USER_NOTIFICATION_QUERY_KEY,
  ADMIN_DASHBOARD_STATUS_QUERY_KEY,
  ADMIN_USER_LIST_QUERY_KEY,
  ADMIN_CHAT_LIST_QUERY_KEY,
  ADMIN_MESSAGE_LIST_QUERY_KEY,
};
