import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/componenets/Header";
import ProviderStore from "@/store/ProviderStore";
import { Toaster } from "react-hot-toast";
import TanstackProvider from "@/hooks/TanstackProvider";
import MainWrapper from "@/componenets/MainWrapper";
import Wrapper from "@/componenets/home/Wrapper";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        cz-shortcut-listen="true"
      >
        <ProviderStore>
          <TanstackProvider>
            <MainWrapper>
              <Toaster />
              <Header />
              <Wrapper> {children}</Wrapper>
            </MainWrapper>
          </TanstackProvider>
        </ProviderStore>
      </body>
    </html>
  );
}
